"""
Real-Time ICU Anomaly Detection and Alerting System.

Implements a streaming vital sign processing pipeline for bedside deployment:
  - Rolling anomaly score computation from incoming vital sign streams
  - Alert triggering with configurable threshold and persistence
  - Alert suppression / cooldown logic to reduce alarm fatigue
  - Dashboard-ready JSON output format
  - Designed for integration with EHR systems (HL7 FHIR, HL7v2)

System requirements for production:
  - Latency: < 500ms per update (achievable on CPU for batch size 1)
  - Input: 1-minute resolution vital signs (1h sliding window minimum)
  - Output: JSON alert events to nurse station dashboard or EHR

Alert logic:
  1. Compute anomaly score from current 6h window
  2. If score >= high_threshold AND persists for >= 2 consecutive updates: HIGH alert
  3. If score >= medium_threshold AND persists >= 1 update: MEDIUM alert
  4. Suppress alerts within cooldown_minutes of last alert (anti-fatigue)
  5. Publish alert JSON to output queue
"""

from __future__ import annotations

import json
import logging
import time
from collections import deque
from dataclasses import asdict, dataclass, field
from datetime import datetime
from typing import Any, Deque, Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
from torch import Tensor

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class VitalSignReading:
    """Single time-stamped vital sign reading."""
    timestamp: datetime
    heart_rate: Optional[float] = None
    sbp: Optional[float] = None
    dbp: Optional[float] = None
    map: Optional[float] = None
    spo2: Optional[float] = None
    resp_rate: Optional[float] = None
    temperature: Optional[float] = None
    gcs: Optional[float] = None

    def to_array(self, channel_order: List[str]) -> np.ndarray:
        """Convert to numpy array in specified channel order."""
        values = []
        for ch in channel_order:
            val = getattr(self, ch, None)
            values.append(float(val) if val is not None else np.nan)
        return np.array(values, dtype=np.float32)


@dataclass
class AlertLevel:
    """Alert severity levels."""
    NONE: str = "NONE"
    LOW: str = "LOW"
    MEDIUM: str = "MEDIUM"
    HIGH: str = "HIGH"
    CRITICAL: str = "CRITICAL"


@dataclass
class AlertEvent:
    """Alert event generated by the monitoring system."""
    patient_id: str
    timestamp: datetime
    alert_level: str
    anomaly_score: float
    channel_scores: Dict[str, float]
    contributing_channels: List[str]
    risk_probabilities: Dict[str, float]
    window_start: datetime
    window_end: datetime
    suppressed: bool = False
    alert_id: str = ""
    message: str = ""
    recommended_action: str = ""

    def to_dict(self) -> dict:
        d = asdict(self)
        d["timestamp"] = self.timestamp.isoformat()
        d["window_start"] = self.window_start.isoformat()
        d["window_end"] = self.window_end.isoformat()
        return d

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)


@dataclass
class DetectorConfig:
    """Configuration for the real-time detector."""
    # Window
    window_hours: int = 6
    step_minutes: int = 5          # re-score every 5 minutes

    # Channels
    channel_names: List[str] = field(default_factory=lambda: [
        "heart_rate", "sbp", "dbp", "map",
        "spo2", "resp_rate", "temperature", "gcs"
    ])

    # Alert thresholds
    high_threshold: float = 0.75     # anomaly score → HIGH
    medium_threshold: float = 0.55   # anomaly score → MEDIUM
    critical_threshold: float = 0.90  # anomaly score → CRITICAL

    # Persistence (anti-chattering)
    high_persistence_steps: int = 2   # must exceed high threshold for N steps
    medium_persistence_steps: int = 1

    # Anti-fatigue cooldown
    cooldown_minutes: int = 30        # suppress alerts within N minutes of last
    max_alerts_per_day: int = 48      # hard cap on daily alerts

    # Normalisation (should match training preprocessing stats)
    channel_means: Optional[Dict[str, float]] = None
    channel_stds: Optional[Dict[str, float]] = None

    # Physiological bounds (for input validation)
    channel_bounds: Optional[Dict[str, Tuple[float, float]]] = None


# ---------------------------------------------------------------------------
# Input validation and normalisation
# ---------------------------------------------------------------------------

class StreamPreprocessor:
    """
    Preprocess incoming vital sign readings for model inference.

    Handles:
      - Out-of-range value rejection
      - Missing value forward-fill
      - Z-score normalisation
    """

    DEFAULT_BOUNDS = {
        "heart_rate":  (20.0,  300.0),
        "sbp":         (40.0,  300.0),
        "dbp":         (20.0,  200.0),
        "map":         (20.0,  200.0),
        "spo2":        (60.0,  100.0),
        "resp_rate":   (4.0,   60.0),
        "temperature": (25.0,  45.0),
        "gcs":         (3.0,   15.0),
    }

    DEFAULT_MEANS = {
        "heart_rate": 84.0, "sbp": 121.0, "dbp": 63.0, "map": 82.0,
        "spo2": 97.0, "resp_rate": 18.0, "temperature": 37.0, "gcs": 13.0,
    }
    DEFAULT_STDS = {
        "heart_rate": 17.0, "sbp": 22.0, "dbp": 14.0, "map": 15.0,
        "spo2": 3.0, "resp_rate": 5.0, "temperature": 0.5, "gcs": 3.0,
    }

    def __init__(self, config: DetectorConfig) -> None:
        self.config = config
        self.bounds = config.channel_bounds or self.DEFAULT_BOUNDS
        self.means = config.channel_means or self.DEFAULT_MEANS
        self.stds = config.channel_stds or self.DEFAULT_STDS

    def validate_reading(self, reading: VitalSignReading) -> Dict[str, Optional[float]]:
        """Filter out-of-range values."""
        result = {}
        for ch in self.config.channel_names:
            val = getattr(reading, ch, None)
            if val is None or np.isnan(val):
                result[ch] = None
                continue
            lo, hi = self.bounds.get(ch, (-np.inf, np.inf))
            result[ch] = float(val) if lo <= val <= hi else None
        return result

    def normalize(self, values: Dict[str, Optional[float]]) -> np.ndarray:
        """Z-score normalise and fill missing with 0 (mean-normalised)."""
        arr = np.zeros(len(self.config.channel_names), dtype=np.float32)
        for i, ch in enumerate(self.config.channel_names):
            val = values.get(ch)
            if val is not None:
                mean = self.means.get(ch, 0)
                std = self.stds.get(ch, 1)
                arr[i] = (val - mean) / max(std, 1e-6)
            # else: leave as 0 (mean-substituted)
        return arr

    def reading_to_tensor(self, reading: VitalSignReading) -> np.ndarray:
        """Full pipeline: validate → normalise → return (C,) array."""
        validated = self.validate_reading(reading)
        return self.normalize(validated)


# ---------------------------------------------------------------------------
# Rolling Buffer
# ---------------------------------------------------------------------------

class RollingVitalBuffer:
    """
    Maintains a rolling window of normalised vital sign arrays.

    Automatically forward-fills missing readings.
    """

    def __init__(
        self,
        window_steps: int,
        n_channels: int,
        max_gap_steps: int = 8,
    ) -> None:
        self.window_steps = window_steps
        self.n_channels = n_channels
        self.max_gap_steps = max_gap_steps
        self._buffer: Deque[np.ndarray] = deque(maxlen=window_steps)
        self._timestamps: Deque[datetime] = deque(maxlen=window_steps)
        self._last_valid: Optional[np.ndarray] = None
        self._gap_count: int = 0

    def push(self, values: np.ndarray, timestamp: datetime) -> None:
        """Add a new reading to the buffer, forward-filling if necessary."""
        # Forward-fill missing channels (nan → last valid value)
        if self._last_valid is not None:
            missing = np.isnan(values) | (values == 0)
            if missing.any():
                # Only fill if within max gap
                if self._gap_count <= self.max_gap_steps:
                    values = np.where(missing, self._last_valid, values)
                self._gap_count += 1
            else:
                self._gap_count = 0
                self._last_valid = values.copy()
        else:
            valid_mask = ~(np.isnan(values) | (values == 0))
            if valid_mask.any():
                self._last_valid = values.copy()

        self._buffer.append(values.copy())
        self._timestamps.append(timestamp)

    def get_window(self) -> Optional[Tensor]:
        """
        Return current window as tensor (1, T, C) if buffer is full.
        Returns None if insufficient data.
        """
        if len(self._buffer) < self.window_steps:
            return None
        arr = np.array(list(self._buffer), dtype=np.float32)  # (T, C)
        arr = np.nan_to_num(arr, nan=0.0)
        return torch.from_numpy(arr).unsqueeze(0)  # (1, T, C)

    def is_ready(self) -> bool:
        return len(self._buffer) >= self.window_steps

    @property
    def window_start(self) -> Optional[datetime]:
        return self._timestamps[0] if self._timestamps else None

    @property
    def window_end(self) -> Optional[datetime]:
        return self._timestamps[-1] if self._timestamps else None


# ---------------------------------------------------------------------------
# Alert State Machine
# ---------------------------------------------------------------------------

class AlertStateMachine:
    """
    Manages alert state including persistence and cooldown logic.

    State transitions:
      NONE → (score > medium_thresh) → PENDING_MEDIUM
      PENDING_MEDIUM → (persists) → MEDIUM alert
      NONE/MEDIUM → (score > high_thresh for N steps) → HIGH alert
      Any → (cooldown active) → suppressed
    """

    def __init__(self, config: DetectorConfig) -> None:
        self.config = config
        self._consecutive_high = 0
        self._consecutive_medium = 0
        self._last_alert_time: Optional[datetime] = None
        self._alerts_today: int = 0
        self._alert_day: Optional[int] = None

    def update(
        self,
        anomaly_score: float,
        timestamp: datetime,
    ) -> Tuple[str, bool]:
        """
        Update state machine with new anomaly score.

        Returns:
            (alert_level, is_new_alert)
        """
        # Reset daily counter
        if self._alert_day != timestamp.day:
            self._alerts_today = 0
            self._alert_day = timestamp.day

        # Determine level from score
        if anomaly_score >= self.config.critical_threshold:
            level = "CRITICAL"
            self._consecutive_high += 1
            self._consecutive_medium += 1
        elif anomaly_score >= self.config.high_threshold:
            level = "HIGH"
            self._consecutive_high += 1
            self._consecutive_medium += 1
        elif anomaly_score >= self.config.medium_threshold:
            level = "MEDIUM"
            self._consecutive_high = 0
            self._consecutive_medium += 1
        else:
            level = "NONE"
            self._consecutive_high = 0
            self._consecutive_medium = 0
            return "NONE", False

        # Check persistence requirements
        if level in ("HIGH", "CRITICAL"):
            if self._consecutive_high < self.config.high_persistence_steps:
                return "PENDING", False
        elif level == "MEDIUM":
            if self._consecutive_medium < self.config.medium_persistence_steps:
                return "PENDING", False

        # Check cooldown
        if self._last_alert_time is not None:
            elapsed_minutes = (timestamp - self._last_alert_time).total_seconds() / 60
            if elapsed_minutes < self.config.cooldown_minutes:
                return level, False  # suppressed by cooldown

        # Check daily cap
        if self._alerts_today >= self.config.max_alerts_per_day:
            return level, False

        # Issue alert
        self._last_alert_time = timestamp
        self._alerts_today += 1
        return level, True


# ---------------------------------------------------------------------------
# Real-Time Detector
# ---------------------------------------------------------------------------

class RealTimeDetector:
    """
    Real-time ICU anomaly detection engine.

    Processes streaming vital sign readings and generates clinical alerts.

    Usage:
        detector = RealTimeDetector(model, config)
        detector.start_patient(patient_id="ICU_001")
        for reading in vital_sign_stream:
            alert = detector.process_reading(patient_id="ICU_001", reading=reading)
            if alert:
                notify_clinical_staff(alert)
    """

    def __init__(
        self,
        model: nn.Module,
        config: Optional[DetectorConfig] = None,
        device: str = "cpu",
    ) -> None:
        self.config = config or DetectorConfig()
        self.model = model.eval()
        self.device = torch.device(device)
        self.model = self.model.to(self.device)

        self.preprocessor = StreamPreprocessor(self.config)
        self.n_channels = len(self.config.channel_names)
        self.window_steps = self.config.window_hours * 12  # assuming 5-min resolution

        # Per-patient state
        self._buffers: Dict[str, RollingVitalBuffer] = {}
        self._state_machines: Dict[str, AlertStateMachine] = {}
        self._alert_histories: Dict[str, List[AlertEvent]] = {}
        self._score_histories: Dict[str, Deque[Tuple[datetime, float]]] = {}

        # Performance tracking
        self._inference_times: Deque[float] = deque(maxlen=100)

    def start_patient(self, patient_id: str) -> None:
        """Initialise monitoring state for a new patient."""
        self._buffers[patient_id] = RollingVitalBuffer(
            window_steps=self.window_steps,
            n_channels=self.n_channels,
        )
        self._state_machines[patient_id] = AlertStateMachine(self.config)
        self._alert_histories[patient_id] = []
        self._score_histories[patient_id] = deque(maxlen=1440)  # 24h at 1-min resolution
        logger.info(f"Started monitoring for patient: {patient_id}")

    def stop_patient(self, patient_id: str) -> None:
        """Clean up patient monitoring state."""
        for d in (self._buffers, self._state_machines,
                   self._alert_histories, self._score_histories):
            d.pop(patient_id, None)
        logger.info(f"Stopped monitoring for patient: {patient_id}")

    @torch.no_grad()
    def process_reading(
        self,
        patient_id: str,
        reading: VitalSignReading,
    ) -> Optional[AlertEvent]:
        """
        Process a single vital sign reading.

        Args:
            patient_id: Patient identifier
            reading:    New vital sign reading

        Returns:
            AlertEvent if an alert is triggered, else None
        """
        if patient_id not in self._buffers:
            self.start_patient(patient_id)

        # Preprocess
        normalised = self.preprocessor.reading_to_tensor(reading)
        self._buffers[patient_id].push(normalised, reading.timestamp)

        if not self._buffers[patient_id].is_ready():
            return None

        # Inference
        t0 = time.perf_counter()
        window = self._buffers[patient_id].get_window().to(self.device)  # (1, T, C)

        try:
            outputs = self.model(window)
        except Exception as e:
            logger.error(f"Inference error for patient {patient_id}: {e}")
            return None

        inference_ms = (time.perf_counter() - t0) * 1000
        self._inference_times.append(inference_ms)

        # Extract scores
        anomaly_score = float(outputs.get("anomaly_score", torch.tensor([0]))[0])
        channel_scores_tensor = outputs.get("channel_scores", torch.zeros(1, self.n_channels))[0]
        channel_scores = {
            ch: float(channel_scores_tensor[i])
            for i, ch in enumerate(self.config.channel_names)
        }

        # Risk probabilities
        risk_probs = {}
        if "outcome_logits" in outputs:
            probs = torch.sigmoid(outputs["outcome_logits"][0])
            outcome_names = getattr(self.model, "outcome_names", ["mortality", "sepsis", "vasopressor"])
            for i, name in enumerate(outcome_names):
                if i < probs.shape[0]:
                    risk_probs[name] = float(probs[i])

        # Record score history
        self._score_histories[patient_id].append((reading.timestamp, anomaly_score))

        # Update alert state machine
        alert_level, is_new_alert = self._state_machines[patient_id].update(
            anomaly_score, reading.timestamp
        )

        if not is_new_alert:
            return None

        # Build alert event
        contributing_channels = [
            ch for ch, sc in sorted(channel_scores.items(), key=lambda x: -x[1])[:3]
            if sc > 0.1
        ]

        alert = AlertEvent(
            patient_id=patient_id,
            timestamp=reading.timestamp,
            alert_level=alert_level,
            anomaly_score=anomaly_score,
            channel_scores=channel_scores,
            contributing_channels=contributing_channels,
            risk_probabilities=risk_probs,
            window_start=self._buffers[patient_id].window_start,
            window_end=reading.timestamp,
            alert_id=f"{patient_id}_{reading.timestamp.strftime('%Y%m%d%H%M%S')}",
            message=self._format_alert_message(alert_level, contributing_channels, risk_probs),
            recommended_action=self._recommend_action(alert_level, risk_probs),
        )

        self._alert_histories[patient_id].append(alert)
        logger.warning(
            f"ALERT [{alert_level}] Patient {patient_id} | "
            f"Score: {anomaly_score:.3f} | "
            f"Channels: {contributing_channels} | "
            f"Inference: {inference_ms:.1f}ms"
        )
        return alert

    def _format_alert_message(
        self,
        level: str,
        contributing_channels: List[str],
        risk_probs: Dict[str, float],
    ) -> str:
        """Generate human-readable alert message."""
        ch_str = ", ".join(c.replace("_", " ").title() for c in contributing_channels[:3])
        risk_str = ""
        for outcome, prob in sorted(risk_probs.items(), key=lambda x: -x[1]):
            if prob > 0.2:
                risk_str += f" P({outcome})={prob:.1%},"

        return (
            f"{level} deterioration alert. "
            f"Abnormal physiological pattern in: {ch_str}."
            f"{' Risk: ' + risk_str.rstrip(',') if risk_str else ''}"
        )

    def _recommend_action(
        self, level: str, risk_probs: Dict[str, float]
    ) -> str:
        """Generate recommended clinical action based on alert level."""
        actions = {
            "CRITICAL": "Immediate bedside assessment. Consider activating rapid response team.",
            "HIGH":     "Urgent bedside assessment within 15 minutes.",
            "MEDIUM":   "Clinical review within 30 minutes. Reassess vital signs.",
            "LOW":      "Increased monitoring frequency. Clinical review at next routine round.",
        }
        action = actions.get(level, "Clinical assessment recommended.")

        # Specific guidance based on risk type
        if risk_probs.get("sepsis", 0) > 0.5:
            action += " Sepsis bundle consideration: blood cultures, lactate, antibiotics."
        elif risk_probs.get("vasopressor", 0) > 0.5:
            action += " Haemodynamic instability: check fluid status, consider vasopressors."

        return action

    def process_batch(
        self,
        patient_id: str,
        readings: List[VitalSignReading],
    ) -> List[Optional[AlertEvent]]:
        """Process a batch of readings for a patient."""
        alerts = []
        for reading in readings:
            alert = self.process_reading(patient_id, reading)
            alerts.append(alert)
        return alerts

    def get_current_status(self, patient_id: str) -> Dict[str, Any]:
        """Get current monitoring status for a patient."""
        if patient_id not in self._buffers:
            return {"status": "not_monitoring"}

        score_history = list(self._score_histories.get(patient_id, []))
        recent_scores = [s for _, s in score_history[-12:]]  # last hour
        alert_history = self._alert_histories.get(patient_id, [])

        current_score = recent_scores[-1] if recent_scores else None
        level = "NONE"
        if current_score is not None:
            if current_score >= self.config.critical_threshold:
                level = "CRITICAL"
            elif current_score >= self.config.high_threshold:
                level = "HIGH"
            elif current_score >= self.config.medium_threshold:
                level = "MEDIUM"

        return {
            "patient_id": patient_id,
            "current_score": current_score,
            "current_level": level,
            "trend": float(np.diff(recent_scores[-3:]).mean()) if len(recent_scores) >= 3 else 0.0,
            "alerts_last_24h": len([
                a for a in alert_history
                if (datetime.utcnow() - a.timestamp).total_seconds() < 86400
            ]),
            "buffer_ready": self._buffers[patient_id].is_ready(),
            "avg_inference_ms": float(np.mean(self._inference_times)) if self._inference_times else None,
        }

    def get_dashboard_payload(self, patient_id: str) -> str:
        """Return JSON payload formatted for bedside dashboard display."""
        status = self.get_current_status(patient_id)
        score_history = list(self._score_histories.get(patient_id, []))
        recent_alerts = [
            a.to_dict() for a in self._alert_histories.get(patient_id, [])[-5:]
        ]

        payload = {
            "patient_id": patient_id,
            "updated_at": datetime.utcnow().isoformat(),
            **status,
            "score_timeline": [
                {"time": t.isoformat(), "score": float(s)}
                for t, s in score_history[-60:]  # last hour
            ],
            "recent_alerts": recent_alerts,
        }
        return json.dumps(payload, indent=2)


# ---------------------------------------------------------------------------
# Monitoring Simulation
# ---------------------------------------------------------------------------

class MonitoringSimulator:
    """
    Simulate real-time monitoring on historical MIMIC data.

    Replays vital signs from a completed ICU stay at configurable speed
    and evaluates alert performance vs. ground truth event times.
    """

    def __init__(
        self,
        detector: RealTimeDetector,
        speed_multiplier: float = 60.0,
    ) -> None:
        self.detector = detector
        self.speed_multiplier = speed_multiplier

    def simulate(
        self,
        patient_id: str,
        vitals_df,  # pd.DataFrame
        event_times: Optional[Dict[str, float]] = None,
        real_time: bool = False,
    ) -> Dict[str, Any]:
        """
        Simulate monitoring for a historical ICU stay.

        Args:
            patient_id:    Identifier for simulation
            vitals_df:     Time-indexed vital sign DataFrame
            event_times:   Dict of clinical event times (hours from ICU admit)
            real_time:     If True, sleep to simulate real-time playback

        Returns:
            simulation_result: dict with alerts, scores, performance vs. events
        """
        self.detector.start_patient(patient_id)
        alerts = []
        score_timeline = []

        icu_intime = vitals_df.index[0]

        for timestamp, row in vitals_df.iterrows():
            reading = VitalSignReading(
                timestamp=timestamp,
                heart_rate=row.get("heart_rate"),
                sbp=row.get("sbp"),
                dbp=row.get("dbp"),
                map=row.get("map"),
                spo2=row.get("spo2"),
                resp_rate=row.get("resp_rate"),
                temperature=row.get("temperature"),
                gcs=row.get("gcs"),
            )

            alert = self.detector.process_reading(patient_id, reading)
            status = self.detector.get_current_status(patient_id)
            score_timeline.append({
                "time": timestamp,
                "score": status.get("current_score", 0),
                "hours_from_admit": (timestamp - icu_intime).total_seconds() / 3600,
            })

            if alert:
                alert_hours = (timestamp - icu_intime).total_seconds() / 3600
                alerts.append({
                    "time": timestamp,
                    "hours_from_admit": alert_hours,
                    "level": alert.alert_level,
                    "score": alert.anomaly_score,
                })

            if real_time:
                time.sleep(60 / self.speed_multiplier)

        # Evaluate vs. ground truth
        performance = self._evaluate_alerts(
            alerts, event_times or {}, icu_intime
        )

        return {
            "patient_id": patient_id,
            "n_alerts": len(alerts),
            "alerts": alerts,
            "score_timeline": score_timeline,
            "performance": performance,
        }

    @staticmethod
    def _evaluate_alerts(
        alerts: List[Dict],
        event_times: Dict[str, float],
        icu_intime,
    ) -> Dict[str, Any]:
        """Evaluate alert performance against known event times."""
        results = {}
        for event_name, event_h in event_times.items():
            first_alert_h = None
            for a in alerts:
                if a["hours_from_admit"] < event_h:
                    first_alert_h = a["hours_from_admit"]
                    break

            results[event_name] = {
                "event_hours": event_h,
                "first_alert_hours": first_alert_h,
                "lead_time": (event_h - first_alert_h) if first_alert_h is not None else None,
                "detected": first_alert_h is not None,
            }
        return results


if __name__ == "__main__":
    from src.models.transformer_detector import TransformerAnomalyDetector

    torch.manual_seed(42)
    model = TransformerAnomalyDetector(
        input_dim=8, d_model=64, n_heads=4, n_layers=2,
        ff_dim=128, seq_len=72, causal=True
    )

    config = DetectorConfig(
        window_hours=1,  # small for testing (1h = 12 steps at 5-min)
        high_threshold=0.5,
        medium_threshold=0.3,
        cooldown_minutes=5,
    )
    detector = RealTimeDetector(model, config)
    detector.start_patient("TEST_001")

    # Simulate 50 readings
    from datetime import timedelta
    base_time = datetime(2024, 1, 1, 8, 0, 0)
    np.random.seed(42)
    alerts = []
    for i in range(50):
        ts = base_time + timedelta(minutes=5 * i)
        reading = VitalSignReading(
            timestamp=ts,
            heart_rate=float(np.random.normal(84, 15)),
            sbp=float(np.random.normal(115, 20)),
            map=float(np.random.normal(80, 12)),
            spo2=float(np.random.normal(97, 2)),
            resp_rate=float(np.random.normal(18, 4)),
            temperature=float(np.random.normal(37, 0.4)),
        )
        alert = detector.process_reading("TEST_001", reading)
        if alert:
            alerts.append(alert)

    status = detector.get_current_status("TEST_001")
    print(f"Current score: {status['current_score']:.4f}")
    print(f"Current level: {status['current_level']}")
    print(f"Alerts generated: {len(alerts)}")
    if alerts:
        print(f"First alert level: {alerts[0].alert_level}")
        print(f"Alert JSON: {alerts[0].to_json()[:200]}...")
    print(f"Avg inference: {status['avg_inference_ms']:.2f}ms")
    print("Real-time detector smoke test passed.")

ALERT_COOLDOWN_MIN = 30  # suppress repeated alerts
